### ISSUE TITLE
Facebook login

### ISSUE THREAD

**Issue by montekaka** [netguru/devise-ios-rails#5]
Getting routing error for login with Facebook

![facebook login](https://cloud.githubusercontent.com/assets/1149779/7904691/e4aff9aa-07ba-11e5-98b4-3d7218291fa7.png)

**Comment by user12121212** [comment]
@montekaka If you look at that routes, their won't anything like GET for `/auth/facebook` 

The routes will be like `auth_facebook_path	POST	/auth/facebook(.:format)	devise_ios_rails/oauth#facebook`

**Comment by blase** [comment]
@user12121212 it expects a hash like:
```
{
  user: {
    provider: 'facebook',
    oauth_token: 'valid_token',
    uid: '1234'
  }
}
```
It only responds to JSON format and is not implemented on the browser side, since that's not the purpose of this gem. @montekaka you should implement it like here: http://railscasts.com/episodes/235-devise-and-omniauth-revised, keeping in mind that fields expected by iOS are called `uid`, `provider` and `oauth_token`.

**Comment by pjurczynski** [comment]
In regards to your question about `(.:format)`
in routes, anything you write in between `()` it's an optional parameter. 
In rails the `(.:format)` is a handy way to state the.. well.. the format of the document you want to get. In this case you could do `GET /users/sign_in.json` - then the server would respond you with a json document.

That being said, I would recommend setting appropriate content-type in HTTP headers instead of `(.:format)`. 
```
Content-Type: application/json
Accept: application/json
```

**Comment by user12121212** [comment]
@blase I see we are using koala here, Where from will it get the app secrets and other details? I'm trying to use it for an android app.

**Comment by blase** [comment]
@user12121212 I'm not sure I understand your question. Secrets are stored in `.env` file and I don't think you need them on Android. Koala is used to verify that the OAuth token is valid and that's it.

We should add some examples on how to use it with Facebook from the command line, so other developers will be able to implement their own solutions.

**Comment by user12121212** [comment]
@blase basically, I don't have to do anything other than `  include DeviseIosRails::OAuth` in user model and routing. right?

**Comment by ryanfelton** [comment]
@user12121212 did you ever get this resolved? 

I'm running into an issue with `strong_params`.  I'm seeing this in my logfile: 
```Unpermitted parameters: provider, oauth_token, uid```

Is my spec formatted correctly?

# spec/requests/users_spec.rb

    require "rails_helper"

    RSpec.describe "Users", :type => :request do
      let(:headers) do
        {
          "CONTENT_TYPE" => "application/json",
          "ACCEPT" => "application/json"
        }
      end

      it "POST /auth/facebook/" do
        post "/users/", '{ "user": { "provider":"facebook", "oauth_token": "abcdefghijklmnopqrstuvwxyz", "uid": "1234567890"} }', headers

        expect(response.content_type).to eq("application/json")
        expect(response).to have_http_status(201)

        data = JSON.parse(response.body)
        expect(data['id']).to be_present
        expect(data['authentication_token']).to be_present
      end
    end

**Comment by user12121212** [comment]
@ryanfelton I somehow managed to solve that issue, But I don't remember how I did that. I'll update here after checking that project.
